### ISSUE TITLE
Is it safest to update to 2.1.7 (or 2.4.2)?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaWeb/MbedTLS.jl#101]
https://tls.mbed.org/tech-updates/releases/mbedtls-2.4.2-2.1.7-and-1.3.19-released

I'm not sure these apply (still above would have non-security bug fixes):

https://tls.mbed.org/tech-updates/security-advisories/mbedtls-security-advisory-2015-01

https://tls.mbed.org/tech-updates/security-advisories/mbedtls-security-advisory-2017-01

**Comment by samoconnor** [comment]
If binary compatibility isn't an issue, not checking the version sounds reasonable to me, however we need to make it clear to the users.
I think the README should say something explicit about: "By default, MbedTLS.jl installs it's own copy of Vxxx of MbedTLS. If ___some_condition___ MbedTLS will use the system MbedTLS library, in this case you should check that your system has the latest security updates"

**Comment by samoconnor** [comment]
So it sounds like the README could say something like "On [platforms X, Y & z] MbedTLS.jl uses mbedtls version 2.7.0. On other platforms it uses the version shipped with the Julia interpreter (see [link])". I think it's important to have a statement like this so that on the day where there is a live vulnerability all over the news people can quickly see if they are exposed to a vulnerable version.

**Comment by samoconnor** [comment]
Related: how would we handle an emergency fix when a new vulnerability is discovered?
e.g.:
 - we've been shipping mbedtls-2.7.0 through bindeps for six months
 - MbedTLS.jl has had various bug fix and enhancement releases.
 - ARM releases 2.7.1 with a binary-compatible fix for a live vulnerability.

If I'm using a 6-month old version of MbedTLS.jl I need a way to install the 2.7.1 lib to fix the vulnerability without being forced to update to the latest MbedTLS.jl (because that might trigger a whole cascade of dependancy updates, or the latest MbedTLS.jl may not support Julia 0.6 anymore, or my release policy says to change the minimal possible set of things for emergency security fixes).

Is there something in Pkg3 that supports emergency fixes?

**Comment by quinnj** [comment]
SGTM

**Comment by tkelman** [comment]
folks have had issues with powershell a little more often than they've had problems with Pkg's connectivity I believe - or not having curl or wget installed, as another example

**Comment by tkelman** [comment]
The system libraries really need to be checking for api compatibility before being used, and introducing a download where previously there wasn't one is going to make the installation more complicated. I don't think the bindeps2 usage is ready to tag at this time. Applying @samoconnor's to a branch that doesn't include the bindeps2 switchover would be much more preferable.

**Comment by quinnj** [comment]
Remember I mentioned that there is no using of system libraries anymore; that's not a thing. You either use prebuilt binaries, julia-shipped binaries, or we try to build from source.

**Comment by tkelman** [comment]
It is a thing if the "julia shipped" paths happen to be system libraries.

**Comment by staticfloat** [comment]
If the “Julia shipped libraries” are system libraries, that means the system libraries are already loaded into Julia, right? So there’s really nothing we can do in that case. If we are talking about a hypothetical future Julia that won’t auto-link in mbedtls then we won’t have a Julia-shipped mbedtls at all, and there will be no system libraries that we would accidentally load.

**Comment by tkelman** [comment]
no, system julia libraries may happen to sit next to too-old system mbedtls libraries that they aren't actually using

**Comment by staticfloat** [comment]
I don’t think that can happen; we put all our Julia libraries inside of ‘lib/julia’ for exactly this reason.

**Comment by tkelman** [comment]
that's not where the code here is looking, it's using `Libdl.dlpath("libmbedtls")` which could be nearly anything

**Comment by staticfloat** [comment]
`Libdl.dlpath("libmbedtls")` will only return a `libmbedtls` that is already loaded, so again, this is doing the right thing.

I personally would change this to `dirname(Libdl.dlpath("libjulia"))` for maximum compatibility against future versions of Julia that may not ship with `libmbedtls`, but in any case, I don't see how this is dangerous.  If someone has already manually `dlopen()`'ed an incorrect `mbedtls`, there's nothing we can do in any case.

**Comment by tkelman** [comment]
If the julia installation doesn't ship with libmbedtls, you absolutely don't want to be looking next to libjulia for it.

`Libdl.dlpath` will try to dlopen whatever it can find if called with a string https://github.com/JuliaLang/julia/blob/dcc39f4d8d45c5fd1ee5ca477af6ad3c23ff01d4/stdlib/Libdl/src/Libdl.jl#L161-L166

**Comment by staticfloat** [comment]
> Libdl.dlpath will try to dlopen whatever it can find if called with a string https://github.com/JuliaLang/julia/blob/dcc39f4d8d45c5fd1ee5ca477af6ad3c23ff01d4/stdlib/Libdl/src/Libdl.jl#L161-L166

I stand corrected.  You're right, we don't want that.

> If the julia installation doesn't ship with libmbedtls, you absolutely don't want to be looking next to libjulia for it.

Sorry, I mistyped previously.  I meant to find `libjulia`, then go into the `"julia"` subdirectory next to it, as that is a more reliable method of finding the private libdir, which I think is what we want.  We want to avoid the scenario of picking up a `libmbedtls`, so we should look for something we know will always exist (`libjulia`) then use that to reference where `libmbedtls` should be.  E.g. what I should have typed is: `joinpath(dirname(Libdl.dlpath("libjulia")), "julia")`

**Comment by tkelman** [comment]
dropping dlpath helps, but looking in bindir has the same issue. @quinnj you really need to get out of the habit of immediately merging and releasing unreviewed changes, especially to security sensitive packages.

**Comment by quinnj** [comment]
How does it have the same issue?

**Comment by quinnj** [comment]
I think a quick merge was totally justified in this case; MbedTLS.jl was essentially broken for all 0.6 users who upgraded (who weren't using 0.6.2 yet).

**Comment by tkelman** [comment]
bindir isn't always private, there can be system packages found there

mark the broken release as requiring 0.6.2 in metadata then. put up the branch, ask people to review and test it, but if you're the only person who's had a chance to look at something that's not a good sign anyone else should be using it yet.

**Comment by quinnj** [comment]
> bindir isn't always private, there can be system packages found there

What does this mean? Why isn't it private? how would system packages get there? just source builds? custom distributions?

**Comment by tkelman** [comment]
either of those.

**Comment by quinnj** [comment]
Well this thread isn't very productive; unless we can spell out specific scenarios (and reliable ways to detect) where we shouldn't trust mbed libraries that show up in the julia-specific bindir, then I don't think there's anything actionable.

I think the only thing that I can come up w/ is printing a warning if we detect a non-current mbed library version.

**Comment by tkelman** [comment]
what do you need explained? if you install julia globally, then unrelated too-old versions of mbedtls may appear next to it and should not be used. restore the version validation that the bindeps code was doing before using any existing copies of libraries. I'm not saying anything new hwre that I haven't been saying for a week or two, what's the difficulty?

**Comment by tkelman** [comment]
Not closed, remains a regression relative to bindeps using versions. Validate libraries before using them.

**Comment by quinnj** [comment]
code to emit a warning for old versions of mbedtls is in #142.
