### ISSUE TITLE
Fail to precompile on windows 7

### ISSUE THREAD

**Issue by YongHee-Kim** [JuliaWeb/MbedTLS.jl#105]
MbedTLS cannot precompile at first Julia run on Atom IDE (clean install with new computer)

``` julia 
PowerShell version < 3 encountered. Running without wrapper (interrupts won't work).
INFO: Precompiling module MbedTLS.
ERROR: LoadError: could not open file C:\Users\kimyonghee\.julia\v0.5\MbedTLS\src\..\deps\deps.jl
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:242
 in _start() at .\client.jl:321
while loading C:\Users\kimyonghee\.julia\v0.5\MbedTLS\src\MbedTLS.jl, in expression starting on line 40
......
```
Creating empty `deps.jl` file on `..\deps\` folder solves this problem and I could've run Julia on Atom IDE. 

here is `versioninfo()`
```
Julia Version 0.5.2
Commit f4c6c9d (2017-05-06 16:34 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by tkelman** [comment]
What is the output of `Pkg.build("MbedTLS")` ? Or if you temporarily move `C:\Users\kimyonghee\.julia\v0.5\MbedTLS` out of the way and re-run `Pkg.add("MbedTLS")`, does anything unusual happen?

**Comment by YongHee-Kim** [comment]
1. Output of Pkg.build("MbedTLS")
- same error occurs without manually creating `deps.jl` 
``` julia 
ERROR: LoadError: could not open file C:\Users\kimyonghee\.julia\v0.5\MbedTLS\src\..\deps\deps.jl
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
```

2. Removing `C:\Users\kimyonghee\.julia\v0.5\MbedTLS` and adding package again
 - MbedTLS can build on its own after doing this.
![image](https://cloud.githubusercontent.com/assets/7087745/26139672/58924c1a-3b0d-11e7-9e65-2ce58f866020.png)

**Comment by tkelman** [comment]
Something probably went wrong the first time you tried to install the package. Without knowing what that was or how to reproduce it I'm not sure there's anything we can do here.

**Comment by YongHee-Kim** [comment]
Okay, I will update this issue if I can specify reproduce step. 
Thanks.

**Comment by samoconnor** [comment]
@tkelman Time to close this issue if there is nothing more to be learned? Probably obsolete given recent bindeps changes anyway...
