### ISSUE TITLE
Failing request for https example from HttpServer

### ISSUE THREAD

**Issue by JockLawrie** [JuliaWeb/MbedTLS.jl#11]
Hi there,

Not sure if this is an issue with MbedTLS.jl or another package, but here it is:

I get HttpServer.jl/examples/https.jl running in one terminal.
In another terminal:
```julia
using Requests
get("https://0.0.0.0:8002")
```

The error is get in the client terminal is:
ERROR: MbedTLS error code -9984: X509 - Certificate verification failed, e.g. CRL, CA or signature failed.

Any ideas?
I am using the latest release of each package, i.e., I'm not using the latest commit on master.

Cheers,
Jock

**Comment by malmaud** [comment]
Does `Pkg.test("MbedTLS")` and `Pkg.test("HttpServer")` pass? If so, it's probably just a problem with the example (although it should still be fixed).

**Comment by JockLawrie** [comment]
Both ``Pkg.test("MbedTLS")`` and ``Pkg.test("HttpServer")`` pass.
Perhaps an issue with ``Requests.jl``?
The full output is:
```julia
get("https://0.0.0.0:8002")
ERROR: MbedTLS error code -9984: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
 [inlined code] from /home/jock/.julia/v0.4/MbedTLS/src/error.jl:4
 in handshake at /home/jock/.julia/v0.4/MbedTLS/src/ssl.jl:3
 in open_stream at /home/jock/.julia/v0.4/Requests/src/streaming.jl:170
 in do_stream_request at /home/jock/.julia/v0.4/Requests/src/Requests.jl:282
 in do_request at /home/jock/.julia/v0.4/Requests/src/Requests.jl:229
 in get at /home/jock/.julia/v0.4/Requests/src/Requests.jl:344
 in get at /home/jock/.julia/v0.4/Requests/src/Requests.jl:343
```

**Comment by malmaud** [comment]
Oh, this is expected. The example generates a self-signed certificate and explicitly instructs the client to trust that certificate. Requests.jl is correctly rejecting that self-signed certificate when you run it from another terminal. If you pass `tls_pass=TLS_NOVERIFY` as a keyword parameter to `get`, it should work.

**Comment by JockLawrie** [comment]
That's a relief.
Now getting:
``ERROR: UndefVarError: TLS_NOVERIFY not defined``

**Comment by malmaud** [comment]
Sorry, some types. It should actually be `tls_conf=Requests.TLS_NOVERIFY`.

**Comment by JockLawrie** [comment]
That worked! Thanks again.
For posterity:
```julia
res = get("https://0.0.0.0:8002", tls_conf = Requests.TLS_NOVERIFY)
utf8(res.data)
```

**Comment by malmaud** [comment]
Sure, no problem. It if *had* worked initially, then we would really would have had a major security problem :)
