### ISSUE TITLE
Error with ECB cipher

### ISSUE THREAD

**Issue by JockLawrie** [JuliaWeb/MbedTLS.jl#12]
Not urgent,  but recording this issue in case it is a symptom of a bigger issue:
```julia
using MbedTLS

msg         = "Testing ECB encryption"
secret_key  = rand(UInt8, 32)
cipher_text = encrypt(MbedTLS.CIPHER_AES_256_ECB, secret_key, msg)
```
The output I get is:
```
ERROR: MbedTLS error code -25216: CIPHER - Decryption of block requires a full block
 [inlined code] from /home/jock/.julia/v0.4/MbedTLS/src/error.jl:4
 in crypt! at /home/jock/.julia/v0.4/MbedTLS/src/cipher.jl:3
 in crypt at /home/jock/.julia/v0.4/MbedTLS/src/cipher.jl:290
 in encrypt at /home/jock/.julia/v0.4/MbedTLS/src/cipher.jl:316
```

**Comment by malmaud** [comment]
After some investigation, I've found that mbedtls doesn't support padding for ECB, although it does have padding for CBC and all the other actively-used block modes.

**Comment by malmaud** [comment]
I'll just leave this here for reference: https://github.com/ARMmbed/mbedtls/issues/342#issuecomment-152855932
