### ISSUE TITLE
upgrading from 0.5.5 to 0.5.8 doesn't rebuild deps correctly

### ISSUE THREAD

**Issue by s2maki** [JuliaWeb/MbedTLS.jl#135]
Unless I manually delete `deps/usr`, the content of `deps/deps.jl` remains as it was for 0.5.5, which on the Mac is merely
```
const MBED_TLS = "libmbedtls"
const MBED_CRYPTO = "libmbedcrypto"
const MBED_X509 = "libmbedx509"
```
rather than the content generated by BinaryProvider.

**Comment by staticfloat** [comment]
Do you still have the contents of `deps/usr` around to show me what's inside of them?

**Comment by s2maki** [comment]
Yes.  The contents of `deps/usr` from 0.5.5 are identical to the contents in the 0.5.8 version.  If I delete `deps/usr` in 0.5.8 and run `Pkg.build("MbedTLS")`, then diff the 0.5.5 and 0.5.8 versions, there are no differences.
