### ISSUE TITLE
Error in Pkg.build(MbedTLS)

### ISSUE THREAD

**Issue by ChiaraCCC** [JuliaWeb/MbedTLS.jl#147]
![error](https://user-images.githubusercontent.com/38471135/38883903-78b399b8-426e-11e8-8a67-f1cceb726e9d.JPG)

Could you please help me with this issue?

**Comment by samoconnor** [comment]
I think the `System.Net.SecurityProtocolType` error means that you need a windows update. @quinnj? @staticfloat? 
See: https://github.com/JuliaWeb/MbedTLS.jl/issues/133#issuecomment-373969449

**Comment by tnarukawa** [comment]
I solved the build error by manually downloading the latest versions of "MbedTLS.x86_64-w64-mingw32.tar.gz" and "build.jl"  via "https://github.com/JuliaWeb/MbedTLSBuilder/releases".
You can build MbedTLS by placing the downloaded files in directories "...\ MbedTLS \ deps \ usr \ downloads" and "...\ MbedTLS \ deps", respectively.
