### ISSUE TITLE
tls.mbed.org is not responding

### ISSUE THREAD

**Issue by tmlbl** [JuliaWeb/MbedTLS.jl#17]
Leaving me unable to install the package. Should it be able to fall back to something more reliable, like GitHub releases? https://github.com/ARMmbed/mbedtls/releases

**Comment by tmlbl** [comment]
It appears to be back up now, but in case it is of any interest, here are the changes I made to get it to build from GitHub sources:

https://github.com/tmlbl/MbedTLS.jl/commit/c4a352e9f04b18263202a5714f770acf4c011e4b

**Comment by tkelman** [comment]
That could work for the apache version. It would be good to keep the GPL option, which requires the tls.mbed.org download. https://github.com/JuliaWeb/MbedTLS.jl/pull/18 should mitigate this if it happens again.
