### ISSUE TITLE
deps.jl requires root

### ISSUE THREAD

**Issue by turtleslow** [JuliaWeb/MbedTLS.jl#38]
On adding the package on my system, deps.jl contained the following line:

`@checked_lib MBED_TLS "/usr/lib64/libmbedtls.so.9"`

This file does not exist on my system (likely because I denied the requested root access during build).

I found libmbedtls.so.10 (and it's symlink libmbedtls.so) in MbedTLS/deps/src/mbedtls-2.1.1/library so I changed the line in deps.jl to the following (not sure it's that 100% correct, but the package is doing what I need it to do for now):

`@checked_lib MBED_TLS "/home/user/.julia/v0.4/MbedTLS/deps/src/mbedtls-2.1.1/library/libmbedtls.so"`

Should root access really be required?  Can the default build be adjusted to look for the file in the package directory rather than /usr/lib64?

**Comment by yuyichao** [comment]
You likely have a stale build.

**Comment by turtleslow** [comment]
What leads you to believe my build is stale?  I got the build via Pkg.add() a few hours ago.  Are you saying that build is stale?

**Comment by turtleslow** [comment]
@yuyichao, can you clarify?

**Comment by yuyichao** [comment]
It seems that you've done something that confuses `BinDeps` causing it to generate the wrong `deps.jl` file. If `Pkg.build(...)` after deleting `deps/deps.jl` doesn't fix the problem it might be a `BinDeps` bug.
