### ISSUE TITLE
Build Error of MbedTLS.jl on win 7 x64 julia 0.4.2

### ISSUE THREAD

**Issue by cnzxcxt1** [JuliaWeb/MbedTLS.jl#41]
Could you tell me how to solve this problems, please?
It has troubled me for a whole day.
Thanks.
julia> Pkg.build("MbedTLS")
INFO: Building MbedTLS
===============================[ ERROR: MbedTLS ]===============================

LoadError: No download agent available; install curl, wget, or fetch.
while loading C:\Users\digiplante.julia\v0.4\MbedTLS\deps\build.jl, in expressi
on starting on line 69
# 
# 

WARNING: MbedTLS had build errors.
- packages with build errors remain installed in C:\Users\digiplante.julia\v0.4
- build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
- build a single package by running its `deps/build.jl` script
#

**Comment by rohitvarkey** [comment]
> LoadError: No download agent available; install curl, wget, or fetch.

This seems to be the issue. Can you try `Pkg.build("MbedTLS")` after installing one of these?

**Comment by tkelman** [comment]
On windows, none of curl, wget, or fetch are particularly trivial to install. BinDeps should be using powershell there though. What version of Windows are you on?

**Comment by cnzxcxt1** [comment]
@tkelman I am on Windows 7 x64

**Comment by tkelman** [comment]
What does `Pkg.status()` say? How about ```success(`powershell -NoProfile -Command ""`)``` ?

**Comment by cnzxcxt1** [comment]
@tkelman 
julia> Pkg.status()
1 required packages:
 - Atom                          0.4.2
28 additional packages:
 - BinDeps                       0.3.21
 - Blink                         0.3.4
 - CodeTools                     0.3.0
 - Codecs                        0.1.5
 - Compat                        0.7.17
 - FactCheck                     0.4.2
 - Hiccup                        0.0.2
 - HttpCommon                    0.2.4
 - HttpParser                    0.1.1
 - HttpServer                    0.1.5
 - JSON                          0.5.0
 - JuliaParser                   0.6.4
 - LNR                           0.0.2
 - Lazy                          0.10.1
 - LibExpat                      0.1.2
 - MacroTools                    0.3.0
 - MbedTLS                       0.2.2
 - Media                         0.1.2
 - Mustache                      0.0.14
 - Mux                           0.2.0
 - Nettle                        0.2.3
 - Reexport                      0.0.3
 - Requires                      0.2.2
 - SHA                           0.1.2
 - URIParser                     0.1.3
 - WebSockets                    0.1.2
 - WinRPM                        0.1.15
 - Zlib                          0.1.12

**Comment by cnzxcxt1** [comment]
@tkelman 
julia> success(`powershell -NoProfile -Command ""`)
ERROR: could not spawn `powershell -NoProfile -Command ''`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:262

**Comment by tkelman** [comment]
What is `ENV["PATH"]`? Have you or some installed programs been removing system directories from tour path? Powershell is installed by default on all versions of Windows since Vista, and it should be visible on the path unless someone has intentionally broken it.

**Comment by cnzxcxt1** [comment]
@rohitvarkey 
after having installed wget, I have the following error.
julia> Pkg.build("MbedTLS")
INFO: Building MbedTLS
INFO: Attempting to Create directory C:\Users\digiplante\.julia\v0.4\MbedTLS\deps\downloads
INFO: Directory C:\Users\digiplante\.julia\v0.4\MbedTLS\deps\downloads already created
INFO: Downloading file https://cache.julialang.org/https://malmaud.github.io/files/mbedtls-2.1.1-r1.zip
INFO: Done downloading file https://cache.julialang.org/https://malmaud.github.io/files/mbedtls-2.1.1-r1.zip
INFO: Attempting to Create directory C:\Users\digiplante\.julia\v0.4\MbedTLS
INFO: Directory C:\Users\digiplante\.julia\v0.4\MbedTLS already created

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\digiplante\.julia\v0.4\MbedTLS\deps\downloads\mbedtls-2.1.1-r1.zip

Error: Can not open file as archive

===============================[ ERROR: MbedTLS ]===============================

LoadError: failed process: Process(`7z x 'C:\Users\digiplante\.julia\v0.4\MbedTLS\deps\downloads\mbedtls-2.1.1-r1.zip' -
y '-oC:\Users\digiplante\.julia\v0.4\MbedTLS\deps'`, ProcessExited(2)) [2]
while loading C:\Users\digiplante\.julia\v0.4\MbedTLS\deps\build.jl, in expression starting on line 69

================================================================================

====================================================[ BUILD ERRORS ]====================================================


WARNING: MbedTLS had build errors.

 - packages with build errors remain installed in C:\Users\digiplante\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================

**Comment by cnzxcxt1** [comment]
@tkelman C:\Program Files\7-Zip;C:\Users\digiplante\AppData\Local\Julia-0.4.5\bin;C:\Program Files (x86)\GnuWin32\bin;D:\Python27\Scripts;C:\Program Files\Java\jdk1.8.0_20;\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;D:\Program Files\Ultimate_2012\VC\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin;C:\myinstallpro\CodeBlocks\MinGW\bin;C:\myinstallpro\MPICH2\bin;D:\Perl64\site\bin;D:\Perl64\bin;D:\Python27\;D:\Program Files\MiKTeX 2.9\miktex\bin\x64\;D:\CTEX\CTeX\ctex\bin;D:\CTEX\CTeX\cct\bin;D:\CTEX\CTeX\ty\bin;D:\CTEX\Ghostscript\gs9.05\bin;D:\CTEX\GSview\gsview;D:\CTEX\WinEdt;C:\Program Files\ggobi;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Windows\system32;C:\Windows;C:\Windows\system32\wbem

**Comment by cnzxcxt1** [comment]
@tkelman So I have no Powershell in my path? how to fix it?

**Comment by rohitvarkey** [comment]
@cnzxcxt1 @tkelman is the expert when it comes to Windows! 😄 
But your latest issue seems similar to https://github.com/JuliaWeb/MbedTLS.jl/issues/39.

**Comment by tkelman** [comment]
On my system powershell is in `C:\Windows\System32\WindowsPowerShell\v1.0` which should be on the path by default. I don't know why it's missing from yours.

**Comment by staticfloat** [comment]
@tkelman that path is standard enough we may want to just append it to `PATH` if it exists, automatically.

**Comment by staticfloat** [comment]
The .zip file is failing SHA check for me now that the check is being enforced on BinDeps `master`.  Someone with a windows machine should verify that a clean download of the file can extract properly using the `7z` tools.  For the record, the checksum I'm getting on download now is `ae10d5fea059faa949293669557c52ec50a1b0c9798835452ea2130e990b251a`

**Comment by tkelman** [comment]
see https://github.com/staticfloat/cache.julialang.org/issues/10

**Comment by tkelman** [comment]
Jon subtly broke everything months ago but nobody seemed to notice until today :)
https://github.com/JuliaWeb/MbedTLS.jl/commit/0e0ef7fd8af94e7fd5886ba1e7eb48a7c2abdab8#commitcomment-13377994

**Comment by malmaud** [comment]
We must break the current world before we can rebuild a better one.

**Comment by Datseris** [comment]
Can someone tell me how to solve this problem? I probably have the same issue with the original poster. But nowhere in this discussion a solution is presented... 
I am using windows 10 (64-bit).

**Comment by tkelman** [comment]
`ENV["PATH"] *= ";C:\\Windows\\System32\\WindowsPowerShell\\v1.0"` and figure out how or why that location is not on your path, who or what was responsible for removing it.

**Comment by quinnj** [comment]
Should be fixed on master since we now use the julia-shipped mbed shared libraries: https://github.com/JuliaWeb/MbedTLS.jl/pull/81
