### ISSUE TITLE
Adding self-signed certificate

### ISSUE THREAD

**Issue by dfdx** [JuliaWeb/MbedTLS.jl#47]
I'm using `Requests.jl` to access our internal server that uses self-signed certificate. On my Linux Mint I've installed certificate into `/usr/share/ca-certificates/extra/ServerCA.crt` and ran `sudo dpkg-reconfigure ca-certificates` as suggested in [this](http://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate) question. Now I can make calls to our server using `wget`, however using `Requests.jl` fails with MbedTLS error:

> ERROR: MbedTLS error code -9984: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
  [inlined code] from /home/username/.julia/v0.4/MbedTLS/src/error.jl:4
  in handshake at /home/username/.julia/v0.4/MbedTLS/src/ssl.jl:131
  in open_stream at /home/username/.julia/v0.4/Requests/src/streaming.jl:209
  in do_stream_request at /home/username/.julia/v0.4/Requests/src/Requests.jl:350
  in do_request at /home/username/.julia/v0.4/Requests/src/Requests.jl:290
  in post at /home/username/.julia/v0.4/Requests/src/Requests.jl:413
  in post at /home/username/.julia/v0.4/Requests/src/Requests.jl:412
  in get_token at /home/username/work/jl/DMPClient/src/core.jl:15
  in call at /home/username/work/jl/DMPClient/src/core.jl:30

As far as I understand, it may be related to: 

1. Incorrect installation of certificate. In this case it's not actually related to this repository, but it might be that someone will notice an error and correct me. 
2. Mbed TLS can't find locally installed certificates. Can we do anything with it? 
3. Self-signed certificate should be attached to a program manually. Is there any API for this?

**Comment by malmaud** [comment]
mbedtls comes bundled with a list of trusted certificates - it doesn't look at any system-installed certificates. There is a API in Requests to specify additional trusted certificates (or to disable verifying certificates entirely), but it isn't documented yet. Can you open an issue on Requests.jl about documenting its SSL api?

**Comment by dfdx** [comment]
Sure!
