### ISSUE TITLE
Unexpected SSL error

### ISSUE THREAD

**Issue by IainNZ** [JuliaWeb/MbedTLS.jl#5]
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-rc1 (2015-09-09 16:07 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-apple-darwin13.4.0

julia> Pkg.installed("Requests")
v"0.3.1"

julia> Pkg.installed("MbedTLS")
v"0.1.3"

julia> import Requests

julia> r = Requests.get("https://img.shields.io/badge/foo-var-red.svg")
ERROR: MbedTLS error code -30592: SSL - A fatal alert message was received from our peer
 [inlined code] from /Users/idunning/.julia/v0.4/MbedTLS/src/error.jl:4
 in handshake at /Users/idunning/.julia/v0.4/MbedTLS/src/ssl.jl:125
 in open_stream at /Users/idunning/.julia/v0.4/Requests/src/streaming.jl:169
 in do_stream_request at /Users/idunning/.julia/v0.4/Requests/src/Requests.jl:190
 in do_request at /Users/idunning/.julia/v0.4/Requests/src/Requests.jl:141
 in get at /Users/idunning/.julia/v0.4/Requests/src/Requests.jl:252
 in get at /Users/idunning/.julia/v0.4/Requests/src/Requests.jl:251
```

`curl` is fine with it:

```
IAINMAC:website idunning$ curl https://img.shields.io/badge/foo-var-red.svg
<svg xmlns="http://www.w3.org/2000/svg" width="57" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="a"><rect width="57" height="20" rx="3" fill="#fff"/></mask><g mask="url(#a)"><path fill="#555" d="M0 0h28v20H0z"/><path fill="#e05d44" d="M28 0h29v20H28z"/><path fill="url(#b)" d="M0 0h57v20H0z"/></g><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"><text x="14" y="15" fill="#010101" fill-opacity=".3">foo</text><text x="14" y="14">foo</text><text x="41.5" y="15" fill="#010101" fill-opacity=".3">var</text><text x="41.5" y="14">var</text></g></svg>
```

**Comment by IainNZ** [comment]
This site also works over HTTP, so I'm just doing that for now.

**Comment by malmaud** [comment]
FWIW, GnuTLS also barfs in the old version of Requests:

```
julia> r = Requests.get("https://img.shields.io/badge/foo-var-red.svg")
ERROR: GnuTLS Exception: GNUTLS_E_FATAL_ALERT_RECEIVED(-12): A TLS fatal alert has been received.
 in handshake! at /Users/malmaud/.julia/v0.3/GnuTLS/src/GnuTLS.jl:334
 in open_stream at /Users/malmaud/.julia/v0.3/Requests/src/Requests.jl:321
 in do_request at /Users/malmaud/.julia/v0.3/Requests/src/Requests.jl:708
 in get at /Users/malmaud/.julia/v0.3/Requests/src/Requests.jl:735
 in get at /Users/malmaud/.julia/v0.3/Requests/src/Requests.jl:734
```

I'll investigate.

**Comment by malmaud** [comment]
Closed via https://github.com/JuliaWeb/MbedTLS.jl/commit/3678e93bb3cddcb4d46e61bf7fd7530b0909ef47.

**Comment by gtsotsos** [comment]
Hi @malmaud ,

I am also getting the same error code on MbedTLS for a different URL. Please refer to below output. 

I also tested the code on an Ubuntu box and get the same error. Base.download manages to get the file.

Any ideas?

Cheers,
Georgios

using Requests;
resp = get("https://accounts.profunds.com/etfdata/ByFund/SPXN-historical_nav.csv");

MbedTLS error code -30592: SSL - A fatal alert message was received from our peer

 in macro expansion at C:\Users\Georgios\.julia\v0.5\MbedTLS\src\error.jl:4 [inlined]
 in handshake(::MbedTLS.SSLContext) at C:\Users\Georgios\.julia\v0.5\MbedTLS\src\ssl.jl:145
 in open_stream(::HttpCommon.Request, ::MbedTLS.SSLConfig, ::Float64, ::Nullable{URIParser.URI}, ::Nullable{URIParser.URI}) at C:\Users\Georgios\.julia\v0.5\Requests\src\streaming.jl:209
 in #do_stream_request#23(::Dict{AbstractString,AbstractString}, ::Void, ::Void, ::Void, ::Array{Requests.FileParam,1}, ::Void, ::Dict{Any,Any}, ::Bool, ::Int64, ::Array{HttpCommon.Response,1}, ::MbedTLS.SSLConfig, ::Bool, ::Bool, ::Bool, ::Nullable{URIParser.URI}, ::Nullable{URIParser.URI}, ::Requests.#do_stream_request, ::URIParser.URI, ::String) at C:\Users\Georgios\.julia\v0.5\Requests\src\Requests.jl:381
 in do_stream_request(::URIParser.URI, ::String) at C:\Users\Georgios\.julia\v0.5\Requests\src\Requests.jl:344
 in #do_request#22(::Array{Any,1}, ::Function, ::URIParser.URI, ::String) at C:\Users\Georgios\.julia\v0.5\Requests\src\Requests.jl:311
 in #get#29(::Array{Any,1}, ::Function, ::URIParser.URI) at C:\Users\Georgios\.julia\v0.5\Requests\src\Requests.jl:444
 in #get#28(::Array{Any,1}, ::Function, ::String) at C:\Users\Georgios\.julia\v0.5\Requests\src\Requests.jl:443
 in get(::String) at C:\Users\Georgios\.julia\v0.5\Requests\src\Requests.jl:443

**Comment by dmargol1** [comment]
I'm getting this same error at work, but only on certain URLs: 

MbedTLS error code -30592: SSL - A fatal alert message was received from our peer
