### ISSUE TITLE
Use mbedTLS binaries shipped with Julia 0.5

### ISSUE THREAD

**Issue by wildart** [JuliaWeb/MbedTLS.jl#54]
Julia 0.5 will be shipped with mbedTLS 2.2.1 binaries, it would be better to use them in the future versions.

**Comment by tkelman** [comment]
were there any API changes? if the bundled binaries pass the validation tests, this should happen automatically

**Comment by wildart** [comment]
No, it's the same version 2.2.1. I guess BinDeps would detect julia provided libs and setup package against them.

**Comment by tkelman** [comment]
The package is using 2.1.1 at the moment - https://github.com/JuliaWeb/MbedTLS.jl/blob/master/deps/build.jl

I'm pretty sure that's insecure and needs to be updated for the sake of 0.4 though.

**Comment by wildart** [comment]
I misread it. Sure update is required. Hopefully, it would be easy with julia shipped binaries.

**Comment by tkelman** [comment]
The validation here should be a lot stricter if there are potential API changes and binaries coming from Julia as well as previously-built (or downloaded) binaries of older versions around. Why didn't your libgit2 work use 2.3.0?

**Comment by wildart** [comment]
When I wrote patch to `libssh2` when 2.2.1 was the last version. As I understand 2.1.5 is a maintenance release now. And it looks like we would require to use it or 2.3.* because of fixes to bignum API.

**Comment by tkelman** [comment]
are there api changes between 2.2 and 2.3, does your patch for libssh2 need changing at all, or should it be a simple version bump and replacing the checksums? if it's the latter I can add it to https://github.com/JuliaLang/julia/pull/17475

**Comment by wildart** [comment]
version bump should work

**Comment by malmaud** [comment]
Are there any action items for me?

**Comment by tkelman** [comment]
it isn't doing this correctly yet, so yes - get it working

**Comment by malmaud** [comment]
Have we figured out why bindeps isn't automatically  finding the bundled binaries? Maybe I'll just add custom logic to build.jl.

**Comment by tkelman** [comment]
Are your bindings up to date with the 2.3 API? Does 2.3 pass your validation checks?

**Comment by malmaud** [comment]
Looking at https://github.com/ARMmbed/mbedtls/blob/development/ChangeLog, there were no API changes between 2.1 and 2.3, so it should be as simple as making sure bindeps picks up the binary.

**Comment by malmaud** [comment]
Hmm, so as far as I can tell, the library in julia/usr/lib passes the validation test. Are we sure that path is checked by BinDeps?

**Comment by tkelman** [comment]
Maybe not. Try a provides(Binaries or something? be sure you use the relative paths for a binary install of julia, not a source install.

**Comment by malmaud** [comment]
I can't actually find where they are in the binary install of Julia, at least on OS X. At least they are not in `Julia-0.6.app/Contents/Resources/julia/lib`.

**Comment by malmaud** [comment]
Oh, NM.

**Comment by malmaud** [comment]
Alright, https://github.com/JuliaWeb/MbedTLS.jl/pull/66 is my attempt at closing this.

**Comment by quinnj** [comment]
Implemented in https://github.com/JuliaWeb/MbedTLS.jl/pull/81
