### ISSUE TITLE
No sphinx-doc.rb file while building.

### ISSUE THREAD

**Issue by floringogianu** [JuliaWeb/MbedTLS.jl#68]
On `julia 0.4.6`, OSX ElCapitan I get this error while trying to build MbedTLS.

```
julia> Pkg.build("MbedTLS")
INFO: Building Homebrew
Already up-to-date.
INFO: Building MbedTLS

====[ ERROR: MbedTLS]====

LoadError: SystemError: opening file /Users/florin/.julia/v0.4/Homebrew/deps/usr/Library/Formula/sphinx-doc.rb: No such file or directory
while loading /Users/florin/.julia/v0.4/MbedTLS/deps/build.jl, in expression starting on line 74

====[ BUILD ERRORS ]====

WARNING: MbedTLS had build errors.

 - packages with build errors remain installed in /Users/florin/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
 - build a single package by running its `deps/build.jl` script
```

**Comment by daturkel** [comment]
I am having the same issue. OS X El Capitan, deleted .julia, fresh install of 0.4.6, same exact error message.

**Comment by malmaud** [comment]
Looks like a recent update to Homebrew might be responsible. Pinging @staticfloat

**Comment by daturkel** [comment]
I'm guessing you're right, @malmaud. The error references `/Users/XXXXX/.julia/v0.4/Homebrew/deps/usr/Library/Formula/sphinx-doc.rb` but `/Users/XXXXX/.julia/v0.4/Homebrew/deps/usr/Library` doesn't even contain a folder called `Formula`.

**Comment by staticfloat** [comment]
We've released a new version of Homebrew that has adapted to the changed file layout, please try again.

**Comment by daturkel** [comment]
Can confirm that with new homebrew, the issue is fixed for me. I ran:
```
Pkg.rm("Homebrew")
Pkg.checkout("Homebrew")
Pkg.build("Homebrew")
Pkg.build("MbedTLS")
```
and everything worked as it should.
thanks @staticfloat !

**Comment by floringogianu** [comment]
Thanks @staticfloat, everything is fine now.
