### ISSUE TITLE
MbedTLS build error => cannot use HttpServer

### ISSUE THREAD

**Issue by JockLawrie** [JuliaWeb/MbedTLS.jl#7]
Hi there,

I've just got Julia 0.4.0-rc1 up and running. `using HttpServer` fails because MbedTLS.jl isn't building properly. See images below. Any ideas?

Cheers,
Jock

![httpserver_fail](https://cloud.githubusercontent.com/assets/11449078/9865287/77811630-5b97-11e5-9685-9df1ea1e03d6.PNG)

![mbedtls_fail](https://cloud.githubusercontent.com/assets/11449078/9865311/a5438c1a-5b97-11e5-8f90-988a44c96800.PNG)

**Comment by malmaud** [comment]
You need to install cmake, the build tool used by mbedtls. I will clarify that in the read me.

**Comment by JockLawrie** [comment]
Yep, that worked. Thanks.
