### ISSUE TITLE
Build fails due to cmake_check.sh permissions

### ISSUE THREAD

**Issue by micahjsmith** [JuliaWeb/MbedTLS.jl#75]
I had a build failure executing the line `./cmake_check.sh`. Although I don't have the exact build output anymore, I found the issue by testing from the shell:

```
[micahsmith@DESKTOP-UI64NVB deps (detached*)]$ ./cmake_check.sh
-bash: ./cmake_check.sh: Permission denied
[micahsmith@DESKTOP-UI64NVB deps (detached*)]$ ll
total 260K
-rw-rw-r-- 1 micahsmith micahsmith 2.6K Sep 27 01:45 build.jl
-rw-rw-r-- 1 micahsmith micahsmith 253K Sep 27 01:45 cacert.pem
-rw-rw-r-- 1 micahsmith micahsmith  156 Sep 27 01:45 cmake_check.sh
[micahsmith@DESKTOP-UI64NVB deps (detached*)]$ chmod u+x cmake_check.sh
[micahsmith@DESKTOP-UI64NVB deps (detached*)]$ ./cmake_check.sh
```

The build then completed successfully. I'm not sure why the permissions were not set up correctly. If it's applicable, I am trying to build on Windows Subsystem for Linux, and sometimes permissions can be strange due to the underlying Windows filesystem.

**Comment by quinnj** [comment]
Should be fixed on master since https://github.com/JuliaWeb/MbedTLS.jl/pull/81 was merged.
