### ISSUE TITLE
readavailable blocks, but readbytes! doesn't

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/MbedTLS.jl#89]

**Comment by samoconnor** [comment]
It looks to me as if `readbytes!` will block in the current code: https://github.com/JuliaWeb/MbedTLS.jl/blob/master/src/ssl.jl#L238
`readbytes!` calls `unsafe_read` and that has a loop `while nread < nbytes`.

However, the spec for `readbytes!` says that it is non-blocking:
```julia
help?> readbytes!
search: readbytes!

  readbytes!(stream::IO, b::AbstractVector{UInt8}, nb=length(b))

  Read at most nb bytes from stream into b, returning the number of bytes read.
       ^^^^^^^
```

But, for TCPSocket, `readbytes!` is blocking: https://github.com/JuliaLang/julia/blob/master/base/stream.jl#L696

So it is probably best for now that MbedTLS.jl follows the TCPSocket behaviour.

This all needs to be sorted out at some point per: https://github.com/JuliaLang/julia/issues/24526

So, unless this is causing a current problem, should we close this issue @quinnj ?
(I'm thinking that part of sorting out [#24526](https://github.com/JuliaLang/julia/issues/24526) will be making an AbstractIO validation tool, at which point we should test MbedTLS against that)
