### ISSUE TITLE
HMAC and encryption using MbedTLS.jl

### ISSUE THREAD

**Issue by JockLawrie** [JuliaWeb/MbedTLS.jl#9]
Hi there,
I am implementing secure sessions which requires:
- Cryptographically secure RNG
- HMAC with a user-defined key
- Encryption with a user-defined key

So far I have used MbedTLS.jl for the CSRNG and Nettle.jl for HMAC and encryption, see code examples below.
```julia
function csrng(numbytes::Integer)
    # Cyrptographically secure RNG
    entropy = MbedTLS.Entropy()
    rng     = MbedTLS.CtrDrbg()
    MbedTLS.seed!(rng, entropy)
    rand(rng, numbytes)
end

hmac_signature       = digest("sha256", secret_key, arr_uint8)    # Uses Nettle.jl
encrypted_secret_key = encrypt("AES256", symm_key, secret_key)    # Uses Nettle.jl
```

Ideally it would be nice to drop the dependence on Nettle.jl and use MbedTLS.jl for all crypto related functions. I've had a go but without much success.

I can get hashing working as ```hash(MbedTLS.SHA256, arr_uint8)```, but this ignores the user-defined secret key in the example above.

For encryption, again I'm not sure where the user-defined secret key comes into it...and I can't get it working anyway.
```julia
entropy = MbedTLS.Entropy()
rng     = MbedTLS.CtrDrbg()
MbedTLS.seed!(rng, entropy)

ctx = MbedTLS.PKContext()
plaintext  = "This is some plaintext"
ciphertext = zeros(UInt8, length(plaintext))
MbedTLS.encrypt!(ctx, plaintext, ciphertext, rng)    # Error is raised here: Bad input parameters to function
```

Are there simple fixes to my code for HMAC and encryption with a user-defined key? Or do these features not yet exist in MbedTLS.jl?

Thanks for the great work on MbedTLS.jl,
Jock

**Comment by malmaud** [comment]
Hi Jock,
You're very welcome.

I initially focused MbedTLS.jl on wrapping just the parts of MbedTLS essential for supporting https. When I get some time, I'll look into whether MbedTLS supports the operations you're talking about (I suspect it does) and then wrap them. Or if you (or anyone else) beat me to it and submit a PR, that would also work.

**Comment by JockLawrie** [comment]
I totally understand your focus to date. This isn't urgent, just a nice-to-have (though it's probably important for the web stack in the long run to have a consistent and well-tested set of crypto functions). For now the current use of both MbedTLS and Nettle works fine.

To be honest I'm unlikely to submit a PR about this because I'm already drowning in various projects and don't have the head space to get my head around MbedTLS...and I'm not a crypto/security expert (or even amateur), but that's another issue.

**Comment by malmaud** [comment]
Alright, got the HMAC working: `digest(MD_SHA256, "my message", "my key")`. 

Now just have to do the symm crypto.

**Comment by malmaud** [comment]
Closed by https://github.com/JuliaWeb/MbedTLS.jl/commit/a0c63d27ab0bddf27813e06a79386a43c44bf4ba.

You can now do `encrypt(CIPHER_AES, symm_key, msg)`.
